language: python
python: 3.7

# To turn off cached cython files and compiler cache
# set NOCACHE-true
# To delete caches go to https://travis-ci.org/OWNER/REPOSITORY/caches or run
# travis cache --delete inside the project directory from the travis command line client
# The cache directories will be deleted if anything in ci/ changes in a commit 
cache:
  ccache: true
  directories:
    - $HOME/.cache # cython cache
    - $HOME/.ccache # compiler cache
    
addons:
  apt:
    packages:
    - xvfb
env:
  global:
    # create a github personal access token
    # cd pandas-dev/pandas
    # travis encrypt 'PANDAS_GH_TOKEN=personal_access_token' -r pandas-dev/pandas
    - secure: "EkWLZhbrp/mXJOx38CHjs7BnjXafsqHtwxPQrqWy457VDFWhIY1DMnIR/lOWG+a20Qv52sCsFtiZEmMfUjf0pLGXOqurdxbYBGJ7/ikFLk9yV2rDwiArUlVM9bWFnFxHvdz9zewBH55WurrY4ShZWyV+x2dWjjceWG5VpWeI6sA="

git:
  # for cloning
  depth: false

matrix:
  fast_finish: true

  include:
    - python: 3.7
      arch: arm64
      env:
        - JOB="build_wheel" PIP_NO_CACHE_DIR=on
      deploy:
        provider: pypi
        user: mkp2020
        password:
          secure: lIfxbslOqXRyXh76x/CSXhWU5Ct+f5A8YqPlwFo/OjjAId2FW1Fqal2gdBWKcdB5tTKGxdq3bxS1R5jHbBmnq5FzgL6qNq5XQZ9KOGyAUnxGMpqKAOlnu6+yEqmNwnauyAR8K2rX6OXttf0Es+Y3VnHAS767c1iyz4u8uVasgn9OoI7qdp4SWL0hMmej9h5OEfKc99UywHFM6xrIBWnXOi0wm7DmFosEGIsZSCn5C0eR4YQVuEaWqlJWNSsItPAC4i821iT5oRoT2xnIGHXnMGOYmik8NclAstge+/N9BzFFATJrg0cfUFjjPehMDFPGGOSyx9kxqtvWzT4kS/cqEeShhjtdy4Kd6jpToP7QTg8qP0SVjiACaCiVCzPZGVzOjM7u1AN26S/ibfD73SVl6OQNDm3cGFmNa8oZMA3jIxFkmUkdh0JIBzJP2hDt30+syvEV8MFW1xhjV9sIILR9OAGBwTd7p/eJBvI/4fABcJ9pNOnLoXlDIoQ78WVnpmrVt+Z3+T3HX60Mw7XTxku5Y9SOUS/cWEegeEtVLWP8jPqAAHFEzG4cma2rRgIi+EQTxEQf5UcP8Fzy1dSdLkeuy4+5RIZwk46B6/WGu7sA8vEgq+Xo7fNL0ljyMDSpR0H7LkAzTgXQ5Y3bONGwandurtVHwoFo4NMZyUu7wvwHhDs=
        on:
          tags: true
          repo: mpmkp2020/pandas
        skip_cleanup: 'true'
        distributions: sdist bdist_wheel  --plat-name manylinux2014_aarch64

    - env:
        - JOB="3.7" ENV_FILE="ci/deps/travis-37.yaml" PATTERN="(not slow and not network and not clipboard)"

before_install:
  - echo "before_install"
  - if [[ "${JOB}" == "build_wheel" ]]; then
      pip install cython;
      pip install numpy;
      pip install wheel;
      python --version;
    fi
  # set non-blocking IO on travis
  # https://github.com/travis-ci/travis-ci/issues/8920#issuecomment-352661024
  - python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
  - source ci/travis_process_gbq_encryption.sh
  - export PATH="$HOME/miniconda3/bin:$PATH"
  - df -h
  - pwd
  - uname -a
  - git --version
  - ./ci/check_git_tags.sh
  # Because travis runs on Google Cloud and has a /etc/boto.cfg,
  # it breaks moto import, see:
  # https://github.com/spulec/moto/issues/1771
  # https://github.com/boto/boto/issues/3741
  # This overrides travis and tells it to look nowhere.
  - export BOTO_CONFIG=/dev/null

install:
  - echo "${JOB}"
  - if [[ "${JOB}" == "build_wheel" ]]; then
      echo "1";
    else
      echo "install start";
      ci/prep_cython_cache.sh;
      ci/setup_env.sh;
      ci/submit_cython_cache.sh;
      echo "install done";
    fi

script:
  - if [ "${JOB}" == "build_wheel" ]; then
      echo "2";
    else
      echo "script start";
      echo "$JOB";
      source activate pandas-dev;
      ci/run_tests.sh;
    fi
after_script:
  - if [ "${JOB}" == "build_wheel" ]; then
      echo "3";
    else
      echo "after_script start";
      source activate pandas-dev && pushd /tmp && python -c "import pandas; pandas.show_versions();" && popd;
      ci/print_skipped.py;
      echo "after_script done";
    fi
